apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: application-gateway
  namespace: demo1
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 18080
      name: http
      protocol: HTTP
    hosts:
    - "*"